[service-port]
resthookmn = 8000
routingapp = 8001
simplehttpserver = 8000
ryu = 8080
ofp = 6633

[venv-path]
venv11 = "../../venv11/bin/python3.11"
venv7 = "../../venv7/bin/python3.7"
ryu-manager-python7 = '../../venv7/bin/ryu-manager'
ryu-manager-python9 = '../../venv9/bin/ryu-manager'

[app-setting]
scenario-multidomain = true
scenario-num-domain = 2

# Topology file stored at 
# ./scenario/mn_network/graphds/<filename>.ds
scenario-topo-file = 'Epoch.graphml'

[app-path]
simplehttpserver = "./scenario/simplehttpserver/http_file_transfer.py"
scenario-dir = './scenario/scenario'
ryuapp-dir = '../../Yet-Another-Ryu-Simple-Network-Monitor/src/ryu-app'
ryuapp-controllerrest = "../../Yet-Another-Ryu-Simple-Network-Monitor/src/ryu-app/controller_rest.py"
ryuapp-flowmanager = '../../flowmanager/flowmanager.py'
sdndb = './sdndb/crawler.py'