[service-port]
resthookmn = 8000
dynamicsdn = 8001
simplehttpserver = 8000
ryu = 8080
ofp = 6653

[venv-path]
venv11 = "../../venv11/bin/python3.11"
venv7 = "../../venv7/bin/python3.7"
ryu-manager-python7 = '../../venv7/bin/ryu-manager'
ryu-manager-python9 = '../../venv9/bin/ryu-manager'

# PYTHONPATH for python project
python-path = "~/Desktop/ryu/RoutingComparasion/RoutingComparation"


[app-path]
simplehttpserver = "./scenario/simplehttpserver/http_file_transfer.py"

scenario-dir = './scenario/scenario'
ryuapp-dir = '../../Yet-Another-Ryu-Simple-Network-Monitor/src/ryu-app'

ryuapp-controllerrest = "../../Yet-Another-Ryu-Simple-Network-Monitor/src/ryu-app/controller_rest.py"
ryuapp-flowmanager = '../../flowmanager/flowmanager.py'
sdndb = './sdndb/crawler.py'